export const dateFormat = 'dddd, MMM D'
export const dateFormatWithYear = 'D MMM YYYY'
export const timeFormat = 'h:mm a'
export const timeFormatExt = 'h:mm a (D MMM)'
export const moneyFormat = '$0,0.00'
